chore: add files to workflow

diff --git a/.github/workflows/protection.yml b/.github/workflows/protection.yml
--- a/.github/workflows/protection.yml
+++ b/.github/workflows/protection.yml
@@ -3,7 +3,8 @@ name: Verificar cambios en archivo protegido
 on:
   pull_request:
     paths:
-      - 'ruta/al/archivo/protegido.ext'  
+      - '.github/workflows/protection.yml'  
+      - '.github/workflows/pull_request.yml'  
 
 jobs:
   check-protected-file:
@@ -11,7 +12,15 @@ jobs:
     steps:
       - name: Verificar cambios en el archivo protegido
         run: |
-          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep 'ruta/al/archivo/protegido.ext')" ]; then
+          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.github/workflows/pull_request.yml')" ]; then
+            echo "::error::El archivo protegido 'ruta/al/archivo/protegido.ext' ha sido modificado. No se permiten cambios en este archivo."
+            exit 1
+          else
+            echo "El archivo protegido no ha sido modificado."
+          fi
+      - name: Verificar cambios en el archivo protegido
+        run: |
+          if [ -n "$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '.github/workflows/protection.yml'')" ]; then
             echo "::error::El archivo protegido 'ruta/al/archivo/protegido.ext' ha sido modificado. No se permiten cambios en este archivo."
             exit 1
           else
